pipeline {
    agent any
    
    parameters {
        string(name: 'login', description: 'Elija un nombre de usuario para login: ')
        string(name: 'nombre', description: 'Nombre del nuevo usuario: ')
        string(name: 'apellido', description: 'Apellido del nuevo usuario: ')
        choice(name: 'departamento', choices: ['contabilidad', 'finanzas', 'tecnología'], description: 'Departamento del nuevo usuario: ')
        booleanParam(name: 'ADD_TO_SUDO', defaultValue: false, description: 'Seleccionar si el usuario tendrá privilegios de sudo: ')
    }
    
    environment {
        TEMP_PASSWORD = sh(script: 'openssl rand -base64 12', returnStdout: true).trim()
    }
    
    stages {
        stage('Crear usuario') {
            steps {
                echo "Creando al usuario con los siguientes datos: "
                echo "login: ${params.login}"
                echo "Nombre: ${params.nombre}"
                echo "Apellido: ${params.apellido}"
                echo "Departamento: ${params.departamento.toLowerCase()}"
                echo "Agregar al grupo sudo: ${params.ADD_TO_SUDO}"
                
                sh """
                    # Crear al usuario con el login, nombre y apellido y la contraseña temporal:
                    sudo useradd -m -c '${params.nombre}, ${params.apellido}' -s /bin/bash ${params.login}
                    echo "${params.login}:${TEMP_PASSWORD}" | sudo chpasswd
                    # Forzar el cambio de contraseña en el siguiente login:
                    sudo chage -d 0 ${params.login}   
                    
                    # Agregar al usuario al grupo del departamento correspondiente:
                    sudo usermod -aG ${params.departamento.toLowerCase()} ${params.login}

                    # Agregar al usuario al grupo sudo si corresponde:
                    ${params.ADD_TO_SUDO ? "sudo usermod -aG sudo ${params.login}" : ""}
                """
            }
        }
    }
    
    post {
        success {
                echo "El usuario '${params.nombre}, ${params.apellido}' fue creado exitosamente."
                echo "El login del usuario es: ${params.login} y el grupo asignado es ${params.departamento}"
                echo "La contraseña temporal para el usuario con login: ${params.login} es: ${env.TEMP_PASSWORD}"
                ${params.ADD_TO_SUDO ? echo "El usuario se agregó al grupo sudo " : echo "El usuario no está agregado al grupo sudo"}
        }
        aborted {
            echo "El proceso de creación de usuario fue abortado."
        }
        failure {
            echo "Hubo un error inesperado"
        }
    }
}
