pipeline {
    agent any
    
    parameters {
        string(name: 'LOGIN', description: 'Login for the new user')
        string(name: 'FULL_NAME', description: 'Name and Last Name of the new user')
        choice(name: 'DEPARTMENT', choices: ['Accounting', 'Technology', 'Finance'], description: 'Department of the new user')
        booleanParam(name: 'ADD_TO_SUDO', defaultValue: false, description: 'Check to add the user to the sudo group')
    }
    
    environment {
        TEMP_PASSWORD = sh(script: 'openssl rand -base64 12', returnStdout: true).trim()
    }
    
    stages {
        stage('Create User') {
            steps {
                echo "Creating user with details:"
                echo "Username: ${params.LOGIN}"
                echo "Full Name: ${params.FULL_NAME}"
                echo "Department: ${params.DEPARTMENT.toLowerCase()}"
                echo "Add to sudo group: ${params.ADD_TO_SUDO}"
                
                sh """
                    # Create the user with specified login, full name, and temporary password
                    sh "sudo useradd -m -d /home/${params.LOGIN} -c '${params.FULL_NAME}' -s /bin/bash ${params.LOGIN}"
                    echo "${params.LOGIN}:${TEMP_PASSWORD}" | sudo chpasswd
                    sudo chage -d 0 ${params.LOGIN}   # Force password change at next login
                    
                    # Add the user to the department group
                    sudo usermod -aG ${params.DEPARTMENT.toLowerCase()} ${params.LOGIN}

                    # Conditionally add the user to the sudo group
                    ${params.ADD_TO_SUDO ? "sudo usermod -aG sudo ${params.LOGIN}" : ""}
                """
                
                echo "Temporary password for ${params.LOGIN}: ${env.TEMP_PASSWORD}"
            }
        }
    }
    
    post {
        always {
            echo "User creation pipeline completed."
        }
    }
}
