pipeline {
    agent any
    
    parameters {
        string(name: 'login', description: 'Login for the new user')
        string(name: 'nombreyapellido', description: 'Name and Last Name of the new user')
        choice(name: 'departamento', choices: ['contabilidad', 'finanzas', 'tecnología'], description: 'Department of the new user')
        booleanParam(name: 'ADD_TO_SUDO', defaultValue: false, description: 'Check to add the user to the sudo group')
    }
    
    environment {
        TEMP_PASSWORD = sh(script: 'openssl rand -base64 12', returnStdout: true).trim()
    }
    
    stages {
        stage('Create User') {
            steps {
                echo "Creating user with details:"
                echo "Username: ${params.login}"
                echo "Full Name: ${params.nombreyapellido}"
                echo "Department: ${params.departamento.toLowerCase()}"
                echo "Add to sudo group: ${params.ADD_TO_SUDO}"
                
                sh """
                    # Create the user with specified login, full name, and temporary password
                    sh "sudo useradd -m -c '${params.nombreyapellido}' -s /bin/bash ${params.login}"
                    echo "${params.login}:${TEMP_PASSWORD}" | sudo chpasswd
                    sudo chage -d 0 ${params.login}   # Force password change at next login
                    
                    # Add the user to the departament group
                    sudo usermod -aG ${params.departamento.toLowerCase()} ${params.login}

                    # Conditionally add the user to the sudo group
                    ${params.ADD_TO_SUDO ? "sudo usermod -aG sudo ${params.login}" : ""}
                """
                
                echo "Temporary password for ${params.login}: ${env.TEMP_PASSWORD}"
            }
        }
    }
    
    post {
        always {
            echo "User creation pipeline completed."
        }
    }
}
