name: Convert README to PDF

on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Convert README.md to PDF
        run: pandoc README.md -o README.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: README-pdf
          path: README.pdf
