name: Convert README to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-latex-extra texlive-fonts-recommended
      - name: Convert README.md to PDF
        run: |
          mkdir -p build
          pandoc README.md -o build/README.pdf --pdf-engine=pdflatex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: README-pdf
          path: build/README.pdf
